# Generated by Django 2.1.3 on 2018-11-24 16:31

import dbmodel.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ControlBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=25)),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[dbmodel.models.check_mac_address], verbose_name='MAC address')),
                ('ipv6_address', models.GenericIPAddressField(editable=False, null=True, protocol='IPv6', verbose_name='IPv6 address')),
                ('port_number', models.IntegerField(default=8802, verbose_name='port number')),
                ('board_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodel.BoardModel', verbose_name='board model')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('min_value', models.FloatField(verbose_name='minimum value')),
                ('max_value', models.FloatField(verbose_name='maximum value')),
                ('precision', models.IntegerField()),
                ('device_type', models.IntegerField(choices=[(0, 'Sensor'), (1, 'Actuator'), (2, 'Sensor/Actuator')], default=0, verbose_name='device type')),
                ('control_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodel.ControlBoard', verbose_name='control board')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exec_code', models.IntegerField(choices=[(0, 'Not started'), (1, 'Not supported'), (2, 'Successful'), (3, 'Error'), (4, 'Communication error'), (5, 'Timeout')], default=0, verbose_name='execution code')),
                ('value', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodel.Device')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('health_state', models.IntegerField(choices=[(0, 'Unknown'), (1, 'Healthy'), (2, 'Error'), (3, 'Device not found')], default=0, verbose_name='healthy state')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodel.Device')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('web_site', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodel.Manufacturer'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodel.DeviceModel', verbose_name='device model'),
        ),
        migrations.AddField(
            model_name='boardmodel',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dbmodel.Manufacturer'),
        ),
    ]
