# Generated by Django 2.1.3 on 2018-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmodel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='device',
            name='min_value',
        ),
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='precision',
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='max_value',
            field=models.FloatField(default=0.0, verbose_name='maximum value'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='min_value',
            field=models.FloatField(default=0.0, verbose_name='minimum value'),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='precision',
            field=models.IntegerField(default=0),
        ),
    ]
