# Generated by Django 2.1.2 on 2018-10-29 00:53

from django.db import migrations, models
import server.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('board_nome', models.CharField(max_length=100, verbose_name='board model')),
                ('port_number', models.IntegerField(default=8802, verbose_name='port number')),
                ('ipv6_address', models.GenericIPAddressField(editable=False, null=True, protocol='IPv6', verbose_name='IPv6 address')),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[server.models.check_mac_address], verbose_name='MAC address')),
                ('last_led_level', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
