# Generated by Django 2.1.2 on 2018-11-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='controlboard',
            old_name='board_nome',
            new_name='board_model',
        ),
    ]
