# Generated by Django 2.2 on 2019-04-29 02:33

from django.db import migrations, models
import webapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControlBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100, unique=True)),
                ('board_model', models.CharField(max_length=100, verbose_name='board model')),
                ('mac_address', models.CharField(max_length=17, unique=True, validators=[webapp.models.check_mac_address], verbose_name='MAC address')),
                ('last_led_level', models.IntegerField(default=0, editable=False)),
            ],
        ),
    ]
