# Generated by Django 2.1.3 on 2019-04-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlboard',
            name='ipv6_address',
        ),
    ]
