DEFINES += PROJECT_CONF_H=\"project-conf.h\"
CFLAGS += -g
CONTIKI_PROJECT = humidity-sensor-calibration
all: $(CONTIKI_PROJECT)

PROJECT_SOURCEFILES += sensors-helper.c

CONTIKI = ../../..
include $(CONTIKI)/Makefile.include
